### ISSUE TITLE
Use SDammann.WepApi.Versioning with swagger

### ISSUE THREAD

**Issue by SvenVandenbrande** [Sebazzz/SDammann.WebApi.Versioning#52]
Anybody already tried to get this tool working with swagger?
I tried some stuff. But i can't get it working. Anybody wo can help me?

**Comment by camhart** [comment]
I'm also trying to figure it out.  If I find anything I'll let you know.

**Comment by jmichaud-ips** [comment]
I am also trying to get it working with Swagger via Swashbuckle.  I can get it to show only the first version listed in MultipleApiVersions.  Changing the version in the drop down box at the top doesn't change anything.

**Comment by LbISS** [comment]
I have got SDammann.Versioning working with Swashbuckle, but that's not the right way it should work.)

In the web-api config:

```
public static void Register(HttpConfiguration config)
{
    ...
    // swagger
    var apiExplorer = config.Services.GetApiExplorer();
    config.EnsureInitialized();
    CorrectVersionedPaths(apiExplorer);
}

private static readonly Regex VersRegex = new Regex(@"Version(?<major>[1-9][0-9]*)\.(?<minor>[0-9]+)\.");

private static void CorrectVersionedPaths(IApiExplorer apiExplorer)
{
    foreach (var apiDesc in apiExplorer.ApiDescriptions)
    {

        var match = VersRegex.Match(apiDesc.RelativePath);

        if (match.Success)
        {
            var versionDot = $"{match.Groups["major"].Captures[0].Value}.{match.Groups["minor"].Captures[0].Value}";
            var versionUnderscore = $"{match.Groups["major"].Captures[0].Value}.{match.Groups["minor"].Captures[0].Value}";

            apiDesc.RelativePath = new StringBuilder(apiDesc.RelativePath)
                .Replace($"Version{versionUnderscore}.", "")
                .Replace("{version}", versionDot.ToLower())
                .ToString();
        }
    }
}
```

In the swashbuckle config:

```
private static readonly Regex VersRegex = new Regex(@"v(?<major>[1-9][0-9]*)\.(?<minor>[0-9]+)");

private static bool ResolveVersionSupportByRouteConstraint(ApiDescription apiDesc, string targetApiVersion)
{
    var match = VersRegex.Match(apiDesc.RelativePath);

    if (match.Success)
    {
        var versParameter = apiDesc.ParameterDescriptions.FirstOrDefault(p => p.Name ==     "version");
        if(versParameter != null)
            apiDesc.ParameterDescriptions.Remove(versParameter);

        return targetApiVersion == $"v{match.Groups["major"].Captures[0].Value}";
    }

    return false;
}
```

**Comment by Phiph** [comment]
HI @LbISS,

I've tried your implementation and it doesn't work for me :( 

How are you deciding on the versioning selector for the API? At the moment I am using 
`
  configuration.Services.Replace(typeof(IHttpControllerSelector),new RouteVersionedControllerSelector(GlobalConfiguration.Configuration));
`

I've been told that this should allow me in my controllers folder to create sub folders VersionX, X being my version numbers. 

Looking at your regex am I correct in thinking you're using Major and Minor versioning? If so how are you handling that?

Thanks :)

Phill

**Comment by SvenVandenbrande** [comment]
Close old issue

**Comment by SvenVandenbrande** [comment]
Close old issue
