### ISSUE TITLE
Integrating Versioning in an already in production API

### ISSUE THREAD

**Issue by parv0888** [Sebazzz/SDammann.WebApi.Versioning#54]
Hi,
Currently there is no way to implement versioning in an already implemented and in production API. What im doing to implement it is

```
config.Routes.MapHttpRoute(
            name: "DefaultVersionedApi", 
            routeTemplate: "api/v{version}/{controller}/{id}",
            defaults: new { id = RouteParameter.Optional });

config.Routes.MapHttpRoute(
            name: "DefaultApi", 
            routeTemplate: "api/{controller}/{id}", 
            defaults: new { id = RouteParameter.Optional });
```

**Comment by Sebazzz** [comment]
What you can try is to implement `IHttpControllerSelector`, and depending on the matched routed call the `DefaultHttpControllerSelector` or the `VersionedHttpControllerSelector` from the library.
